# Generated by Django 4.1.6 on 2023-02-11 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="opening_date",
            new_name="opening_data",
        ),
    ]
