# Generated by Django 4.1.6 on 2023-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_rename_opening_date_movie_opening_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=1)),
                ("birth_date", models.DateField()),
            ],
        ),
    ]
