# Generated by Django 4.1.6 on 2023-02-12 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_actor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="opening_data",
            new_name="opening_date",
        ),
    ]
