# Generated by Django 4.1.6 on 2023-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_review_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="movies.actor"),
        ),
    ]
